version: '3.8'

services:
  db:
    image: postgres:17
    container_name: diary-db
    environment:
      POSTGRES_DB: diary-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: