spring:
  application:
    name: diary-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:diary-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  profiles:
    active: local

server:
  port: 8080
